plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
cloudinary_cloud_name: circleseven
include:
  - admin
theme: minima
gravatar_hash: c7c96a67607f30615596030dc2c3faf7
author: Matthew French
permalink: /:title/
paginate_path: /page/:num/
sass:
  style: compressed
lang: en-GB
markdown: kramdown
description: The portfolio and blog of Matthew French, documenting Digital Art and Technology projects, academic work, and creative coding experiments from Plymouth University. Exploring interactive media, physical computing, and digital culture.
url: https://circleseven.co.uk
related_posts_count: 4
github_username: mfrench71
cloudinary_base_url: https://res.cloudinary.com/circleseven/image/upload
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page
collections:
  pages:
    output: true
    permalink: /:path/
paginate: 12
title: Circle 7
timezone: Europe/London
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - scripts/
  - docs/
email: mail@circleseven.co.uk
baseurl: ''
google_fonts:
  enabled: false
  body_font: Open Sans
  heading_font: Open Sans
cloudinary_default_folder: circle-seven
